# ======== Stage 1: Build ========
FROM gradle:8.1.1-jdk21 AS builder

WORKDIR /home/gradle/project

COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle
COPY src ./src

RUN ./gradlew build -x test

# ======== Stage 2: Run ========
FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

# Spring Boot JAR vom Build kopieren
COPY --from=builder /home/gradle/project/build/libs/demo-0.0.1-SNAPSHOT.jar ./demo.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","demo.jar"]
